create table comment
(
    id                int8 generated by default as identity,
    creation_date     date not null,
    last_edit_date    date not null,
    text              varchar(300) not null,
    inserted_by_id_id int8 not null,
    news_id           int8 not null,
    primary key (id)
);

create table news
(
    id                int8 generated by default as identity,
    creation_date     date not null,
    last_edit_date    date not null,
    text              varchar(2000) not null,
    title             varchar(150),
    inserted_by_id_id int8 not null,
    updated_by_id_id  int8 not null,
    primary key (id)
);

create table news_users
(
    id             int8 generated by default as identity,
    creation_date  date not null,
    last_edit_date date not null,
    name           varchar(20),
    parent_name    varchar(20),
    password       varchar(80) not null,
    surname        varchar(20),
    username       varchar(40) unique not null,
    primary key (id)
);

create table user_roles
(
    user_id int8 not null,
    roles   varchar(20)
);

alter table if exists comment
    add constraint inserted_by_id_id_FK_comment foreign key (inserted_by_id_id) references news_users;

alter table if exists comment
    add constraint news_id_FK_comment foreign key (news_id) references news;

alter table if exists news
    add constraint inserted_by_id_id_FK_news foreign key (inserted_by_id_id) references news_users;

alter table if exists news
    add constraint updated_by_id_id_FK_news foreign key (updated_by_id_id) references news_users;

alter table if exists user_roles
    add constraint user_id_FK_user_roles foreign key (user_id) references news_users;